version: '2'
services:
  db:
    build: ./docker/db
    image: shop-ee-mysql-db
    container_name: shop-ee-mysql-db
  app:
    build: ./docker/application_server
    image: shop-ee-payara-full
    container_name: shop-ee-payara-full
    depends_on:
     - db
    links:
     - db:DATABASE_IP
    ports:
     - "8282:8080"
     - "80:4848"
